/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Status */
        get: operations["runtime_status_api_v1_runtime_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending */
        get: operations["get_spending_api_v1_analytics_spending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/financial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financial */
        get: operations["get_financial_api_v1_analytics_financial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_v1_feedback_get"];
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feedback Status */
        patch: operations["update_feedback_status_api_v1_feedback__feedback_id__patch"];
        trace?: never;
    };
    "/api/v1/scheduled-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_scheduled_inputs_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_scheduled_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduled-inputs/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rule */
        put: operations["update_rule_api_v1_scheduled_inputs__rule_id__put"];
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_scheduled_inputs__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduled-inputs/run-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Due */
        post: operations["run_due_api_v1_scheduled_inputs_run_due_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manual-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Manual Inputs */
        get: operations["list_manual_inputs_api_v1_manual_inputs_get"];
        put?: never;
        /** Create Manual Input */
        post: operations["create_manual_input_api_v1_manual_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manual-inputs/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correct Manual Input */
        put: operations["correct_manual_input_api_v1_manual_inputs__evidence_id__put"];
        post?: never;
        /** Delete Manual Input */
        delete: operations["delete_manual_input_api_v1_manual_inputs__evidence_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_mapping_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping-reviews/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Mapping */
        post: operations["recommend_mapping_api_v1_mapping_reviews_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping-reviews/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Mapping */
        post: operations["preview_mapping_api_v1_mapping_reviews_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping-reviews/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Mapping */
        post: operations["apply_mapping_api_v1_mapping_reviews_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}/enrichment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Enrichment */
        patch: operations["update_enrichment_api_v1_transactions__transaction_id__enrichment_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][] | null;
        };
        /** ApiListMeta */
        ApiListMeta: {
            /** Request Id */
            request_id: string;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Sort */
            sort: string;
        };
        /** ApiListResponse[FeedbackData] */
        ApiListResponse_FeedbackData_: {
            /** Data */
            data: components["schemas"]["FeedbackData"][];
            meta: components["schemas"]["ApiListMeta"];
        };
        /** ApiListResponse[ManualInputData] */
        ApiListResponse_ManualInputData_: {
            /** Data */
            data: components["schemas"]["ManualInputData"][];
            meta: components["schemas"]["ApiListMeta"];
        };
        /** ApiListResponse[ScheduledRuleData] */
        ApiListResponse_ScheduledRuleData_: {
            /** Data */
            data: components["schemas"]["ScheduledRuleData"][];
            meta: components["schemas"]["ApiListMeta"];
        };
        /** ApiListResponse[TransactionViewData] */
        ApiListResponse_TransactionViewData_: {
            /** Data */
            data: components["schemas"]["TransactionViewData"][];
            meta: components["schemas"]["ApiListMeta"];
        };
        /** ApiMeta */
        ApiMeta: {
            /** Request Id */
            request_id: string;
        };
        /** ApiResponse[EnrichmentMutationData] */
        ApiResponse_EnrichmentMutationData_: {
            data: components["schemas"]["EnrichmentMutationData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[FeedbackData] */
        ApiResponse_FeedbackData_: {
            data: components["schemas"]["FeedbackData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[ManualInputDeletionData] */
        ApiResponse_ManualInputDeletionData_: {
            data: components["schemas"]["ManualInputDeletionData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[ManualInputMutationData] */
        ApiResponse_ManualInputMutationData_: {
            data: components["schemas"]["ManualInputMutationData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[MappingRecommendationData] */
        ApiResponse_MappingRecommendationData_: {
            data: components["schemas"]["MappingRecommendationData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[MappingReviewApplyData] */
        ApiResponse_MappingReviewApplyData_: {
            data: components["schemas"]["MappingReviewApplyData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[MappingReviewPreviewData] */
        ApiResponse_MappingReviewPreviewData_: {
            data: components["schemas"]["MappingReviewPreviewData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[MappingReviewWorkspaceData] */
        ApiResponse_MappingReviewWorkspaceData_: {
            data: components["schemas"]["MappingReviewWorkspaceData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[RuntimeStatusData] */
        ApiResponse_RuntimeStatusData_: {
            data: components["schemas"]["RuntimeStatusData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[ScheduledRuleData] */
        ApiResponse_ScheduledRuleData_: {
            data: components["schemas"]["ScheduledRuleData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[ScheduledRunData] */
        ApiResponse_ScheduledRunData_: {
            data: components["schemas"]["ScheduledRunData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[TransactionViewData] */
        ApiResponse_TransactionViewData_: {
            data: components["schemas"]["TransactionViewData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiResponse[dict[str, Any]] */
        ApiResponse_dict_str__Any__: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            meta: components["schemas"]["ApiMeta"];
        };
        /** EnrichmentData */
        EnrichmentData: {
            /** Merchant Name */
            merchant_name: string | null;
            /** Display Name */
            display_name: string;
            /** Default Category */
            default_category: string | null;
            /** Category */
            category: string;
            /**
             * Category Source
             * @enum {string}
             */
            category_source: "merchant_default" | "transaction_override" | "income_default" | "unclassified";
            /** Is Unclassified */
            is_unclassified: boolean;
            /** Review Signals */
            review_signals: string[];
            /** Note */
            note: string | null;
        };
        /** EnrichmentDecisionData */
        EnrichmentDecisionData: {
            /** Merchant Override */
            merchant_override: string | null;
            /** Category Override */
            category_override: string | null;
            /** Note */
            note: string | null;
        };
        /** EnrichmentMutationData */
        EnrichmentMutationData: {
            /** Transaction Id */
            transaction_id: string;
            decision: components["schemas"]["EnrichmentDecisionData"] | null;
            enrichment: components["schemas"]["EnrichmentData"];
            /**
             * Mutation Impact
             * @constant
             */
            mutation_impact: "enrichments_and_projections";
        };
        /** EnrichmentPatchRequest */
        EnrichmentPatchRequest: {
            /** Merchant Override */
            merchant_override?: string | null;
            /** Category Override */
            category_override?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Location */
            location?: (string | number)[];
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** FeedbackContextData */
        FeedbackContextData: {
            /** Runtime */
            runtime?: ("desktop_web" | "android") | null;
            /** Page */
            page?: string | null;
            /** Workspace */
            workspace?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
        };
        /** FeedbackCreateRequest */
        FeedbackCreateRequest: {
            /** Content */
            content: string;
            context?: components["schemas"]["FeedbackContextData"];
        };
        /** FeedbackData */
        FeedbackData: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
            /** Content */
            content: string;
            context: components["schemas"]["FeedbackContextData"];
        };
        /** FeedbackStatusRequest */
        FeedbackStatusRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
        };
        /** HealthData */
        HealthData: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @constant
             */
            service: "family-spending-backend";
            /** Version */
            version: string;
        };
        /** ManualInputData */
        ManualInputData: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Record Id */
            source_record_id: string;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "income" | "expense";
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string | null;
            /** Transaction Id */
            transaction_id: string | null;
            /** Source Role */
            source_role: ("authoritative" | "supporting") | null;
            transaction: components["schemas"]["TransactionData"] | null;
        };
        /** ManualInputDeletionData */
        ManualInputDeletionData: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Transaction Id */
            transaction_id: string;
            /** Transaction Removed */
            transaction_removed: boolean;
            /**
             * Mutation Impact
             * @constant
             */
            mutation_impact: "transactions_and_downstream";
        };
        /** ManualInputMutationData */
        ManualInputMutationData: {
            item: components["schemas"]["ManualInputData"];
            /**
             * Action
             * @enum {string}
             */
            action: "created" | "reused" | "matched";
            /**
             * Mutation Impact
             * @constant
             */
            mutation_impact: "transactions_and_downstream";
        };
        /** ManualInputWriteRequest */
        ManualInputWriteRequest: {
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "income" | "expense";
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Amount */
            amount: number | string;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /** Description */
            description?: string | null;
        };
        /** MappingRecommendationAlternativeData */
        MappingRecommendationAlternativeData: {
            /** Merchant */
            merchant: string;
            /** Category */
            category: string | null;
            /** Rank Score */
            rank_score: number;
            /** Matched Description */
            matched_description: string;
        };
        /** MappingRecommendationData */
        MappingRecommendationData: {
            /** Description */
            description: string;
            /** Merchant */
            merchant: string;
            /** Category */
            category: string | null;
            /** Rank Score */
            rank_score: number;
            /** Score Margin */
            score_margin: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "strong" | "weak" | "drafted";
            /**
             * Origin
             * @enum {string}
             */
            origin: "exact" | "normalized_history" | "history" | "draft";
            /** Is New Merchant */
            is_new_merchant: boolean;
            /**
             * Category Basis
             * @enum {string}
             */
            category_basis: "reviewed_merchant_default" | "keyword" | "none";
            /** Matched Description */
            matched_description: string | null;
            /** Evidence */
            evidence: string[];
            /** Signals */
            signals: {
                [key: string]: number;
            };
            /** Alternatives */
            alternatives: components["schemas"]["MappingRecommendationAlternativeData"][];
            /** Model Version */
            model_version: string;
        };
        /** MappingRecommendationRequest */
        MappingRecommendationRequest: {
            /** Description */
            description: string;
        };
        /** MappingReviewApplyData */
        MappingReviewApplyData: {
            preview: components["schemas"]["MappingReviewPreviewData"];
            /**
             * Mutation Impact
             * @constant
             */
            mutation_impact: "enrichments_and_projections";
        };
        /** MappingReviewApplyRequest */
        MappingReviewApplyRequest: {
            /** Description */
            description: string;
            /** Merchant */
            merchant: string;
            /** Category */
            category: string;
            /** Preview Token */
            preview_token: string;
            /**
             * Confirm New Merchant
             * @default false
             */
            confirm_new_merchant: boolean;
        };
        /** MappingReviewItemData */
        MappingReviewItemData: {
            /** Description */
            description: string;
            /** Transaction Count */
            transaction_count: number;
            /** Total Amount */
            total_amount: string;
            /** Currency */
            currency: string;
            /**
             * Latest Date
             * Format: date
             */
            latest_date: string;
            /** Source Types */
            source_types: string[];
            /** Transaction Only Exception Count */
            transaction_only_exception_count: number;
            recommendation: components["schemas"]["MappingRecommendationData"];
        };
        /** MappingReviewPreviewData */
        MappingReviewPreviewData: {
            /** Token */
            token: string;
            /** Description */
            description: string;
            /** Merchant */
            merchant: string;
            /** Category */
            category: string;
            /** Is New Merchant */
            is_new_merchant: boolean;
            /** Previous Default Category */
            previous_default_category: string | null;
            /** Description Transaction Count */
            description_transaction_count: number;
            /** Description Affected Transaction Count */
            description_affected_transaction_count: number;
            /** Default Category Affected Transaction Count */
            default_category_affected_transaction_count: number;
            /** Total Affected Transaction Count */
            total_affected_transaction_count: number;
            /** Preserved Merchant Exception Count */
            preserved_merchant_exception_count: number;
            /** Preserved Category Exception Count */
            preserved_category_exception_count: number;
        };
        /** MappingReviewRequest */
        MappingReviewRequest: {
            /** Description */
            description: string;
            /** Merchant */
            merchant: string;
            /** Category */
            category: string;
        };
        /** MappingReviewWorkspaceData */
        MappingReviewWorkspaceData: {
            /** Items */
            items: components["schemas"]["MappingReviewItemData"][];
            /** Merchants */
            merchants: components["schemas"]["MerchantMappingOptionData"][];
            /** Categories */
            categories: string[];
        };
        /** MerchantMappingOptionData */
        MerchantMappingOptionData: {
            /** Name */
            name: string;
            /** Default Category */
            default_category: string;
        };
        /** RuntimeCountsData */
        RuntimeCountsData: {
            /** Source Records */
            source_records: number;
            /** Transactions */
            transactions: number;
            /** Enrichments */
            enrichments: number;
            /** Mapping Reviews */
            mapping_reviews: number;
            /** Feedback */
            feedback: number;
        };
        /** RuntimeStatusData */
        RuntimeStatusData: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "starting" | "ready";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Generation */
            generation: number;
            /** Queued Mutations */
            queued_mutations: number;
            /** Last Successful Mutation */
            last_successful_mutation: string | null;
            /** Last Failed Mutation */
            last_failed_mutation: string | null;
            /** Last Imap Poll */
            last_imap_poll: string | null;
            /** Last Scheduler Tick */
            last_scheduler_tick: string | null;
            /** Parser Cache Hits */
            parser_cache_hits: number;
            /** Parser Cache Misses */
            parser_cache_misses: number;
            counts: components["schemas"]["RuntimeCountsData"];
            /** Schema Version */
            schema_version: string;
            /** Parser Version */
            parser_version: string;
        };
        /** ScheduledOccurrenceData */
        ScheduledOccurrenceData: {
            /** Rule Id */
            rule_id: string;
            /**
             * Occurrence Date
             * Format: date
             */
            occurrence_date: string;
            /** Evidence Id */
            evidence_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Transaction Id */
            transaction_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "created" | "matched" | "reused" | "recovered";
        };
        /** ScheduledRuleData */
        ScheduledRuleData: {
            /** Id */
            id: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "income" | "expense";
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Note */
            note: string | null;
            /**
             * Next Date
             * Format: date
             */
            next_date: string;
            /** Last Occurrence Date */
            last_occurrence_date: string | null;
            /** Last Source Record Id */
            last_source_record_id: string | null;
            /** Last Transaction Id */
            last_transaction_id: string | null;
            /** Last Action */
            last_action: ("created" | "matched" | "reused" | "recovered") | null;
        };
        /** ScheduledRuleWriteRequest */
        ScheduledRuleWriteRequest: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "income" | "expense";
            /** Amount */
            amount: number | string;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /** Description */
            description: string;
            /**
             * First Occurrence Date
             * Format: date
             */
            first_occurrence_date: string;
            /** Note */
            note?: string | null;
        };
        /** ScheduledRunData */
        ScheduledRunData: {
            /** Occurrences */
            occurrences: components["schemas"]["ScheduledOccurrenceData"][];
            /**
             * Mutation Impact
             * @enum {string}
             */
            mutation_impact: "no_change" | "transactions_and_downstream";
        };
        /** ScheduledRunRequest */
        ScheduledRunRequest: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
        };
        /** TransactionData */
        TransactionData: {
            /** Id */
            id: string;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "income" | "expense";
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** TransactionViewData */
        TransactionViewData: {
            transaction: components["schemas"]["TransactionData"];
            /** Authoritative Source Record Id */
            authoritative_source_record_id: string;
            /** Description */
            description: string | null;
            enrichment: components["schemas"]["EnrichmentData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runtime_status_api_v1_runtime_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RuntimeStatusData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_spending_api_v1_analytics_spending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__Any__"];
                };
            };
        };
    };
    get_financial_api_v1_analytics_financial_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__Any__"];
                };
            };
        };
    };
    list_feedback_api_v1_feedback_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: ("open" | "resolved") | null;
                sort?: "created_desc" | "created_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiListResponse_FeedbackData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_FeedbackData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_feedback_status_api_v1_feedback__feedback_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_FeedbackData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_rules_api_v1_scheduled_inputs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                enabled?: boolean | null;
                sort?: "next_date_asc" | "next_date_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiListResponse_ScheduledRuleData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_rule_api_v1_scheduled_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledRuleWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ScheduledRuleData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_rule_api_v1_scheduled_inputs__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledRuleWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ScheduledRuleData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_rule_api_v1_scheduled_inputs__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ScheduledRuleData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_due_api_v1_scheduled_inputs_run_due_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ScheduledRunData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_manual_inputs_api_v1_manual_inputs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                sort?: "date_desc" | "date_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiListResponse_ManualInputData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_manual_input_api_v1_manual_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualInputWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ManualInputMutationData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    correct_manual_input_api_v1_manual_inputs__evidence_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualInputWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ManualInputMutationData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_manual_input_api_v1_manual_inputs__evidence_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ManualInputDeletionData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_workspace_api_v1_mapping_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MappingReviewWorkspaceData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommend_mapping_api_v1_mapping_reviews_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MappingRecommendationData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_mapping_api_v1_mapping_reviews_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MappingReviewPreviewData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    apply_mapping_api_v1_mapping_reviews_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingReviewApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MappingReviewApplyData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                transaction_type?: ("income" | "expense") | null;
                description?: string | null;
                category?: string | null;
                is_unclassified?: boolean | null;
                sort?: "date_desc" | "date_asc" | "amount_desc" | "amount_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiListResponse_TransactionViewData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_transaction_api_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TransactionViewData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_enrichment_api_v1_transactions__transaction_id__enrichment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichmentPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_EnrichmentMutationData_"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
